export const PROJECTS = [
  {
    slug: "01-snake",
    title: "Snake",
    hidden: false,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "2D",
    ],
  },
  {
    slug: "02-arkanoid-game",
    title: "Arkanoid",
    hidden: false,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "Canvas",
    ],
  },
  {
    slug: "03-tetris",
    title: "Tetris",
    hidden: false,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "Canvas",
    ],
  },
  {
    slug: "04-pacman",
    title: "Pacman",
    hidden: false,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "Game Loop",
    ],
  },
  {
    slug: "05-pingpong",
    title: "Ping Pong",
    hidden: false,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "Physics",
    ],
  },
  {
    slug: "06-flappy-dino",
    title: "Flappy Dino",
    hidden: false,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "Gravity",
    ],
  },
  {
    slug: "07-orbita",
    title: "Orbita",
    hidden: false,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "Animation",
    ],
  },
  {
    slug: "08-coloron",
    title: "Coloron",
    hidden: false,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "Color Matching",
    ],
  },
  {
    slug: "09-copycat",
    title: "Copycat",
    hidden: false,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "Memory Game",
    ],
  },
  {
    slug: "10-buscaminas",
    title: "Buscaminas",
    hidden: false,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "Logic",
    ],
  },
  {
    slug: "11-towerblocks",
    title: "Tower Blocks",
    hidden: false,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "Physics",
    ],
  },
  {
    slug: "12-ahorcado",
    title: "Ahorcado",
    hidden: false,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "Word Game",
    ],
  },
  {
    slug: "13-simon",
    title: "Simon",
    hidden: false,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "Pattern Recognition",
    ],
  },
  {
    slug: "14-3-en-raya",
    title: "3 en Raya",
    hidden: false,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "Tic-Tac-Toe",
    ],
  },
  {
    slug: "15-hundir-la-flota",
    title: "Hundir la Flota",
    hidden: true,
    learnings: [
      "HTML",
      "CSS",
      "JavaScript",
      "Grid Layout",
    ],
  },
];
